//! Embed the payload.
//!
//! Reads every file in `CHAOS_STAGE_DIR` and writes a Rust source file holding
//! their names and bytes, which `main.rs` includes. That is how one .exe can
//! carry the whole project without a compression library or an archive format:
//! the linker does it.
//!
//! **With no `CHAOS_STAGE_DIR` the payload is empty and the build succeeds.**
//! An installer that refuses to compile unless a release is being cut would
//! break `cargo build --workspace` for everyone, and this crate has to stay in
//! the workspace so its tests run.

use std::fmt::Write as _;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-env-changed=CHAOS_STAGE_DIR");

    let out = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("payload.rs");
    let stage = std::env::var("CHAOS_STAGE_DIR")
        .ok()
        .filter(|s| !s.is_empty());

    let mut src = String::new();
    src.push_str("// GENERATED by build.rs -- do not edit.\n");
    src.push_str("pub struct File { pub name: &'static str, pub bytes: &'static [u8] }\n");

    let mut files: Vec<(String, PathBuf)> = Vec::new();
    if let Some(dir) = &stage {
        println!("cargo:rerun-if-changed={dir}");
        if let Ok(rd) = std::fs::read_dir(dir) {
            for e in rd.flatten() {
                let p = e.path();
                if !p.is_file() {
                    continue;
                }
                let Some(name) = p.file_name().and_then(|n| n.to_str()) else {
                    continue;
                };
                // Never embed the installer in itself: the staging directory is
                // usually the release directory, and one pass would double the
                // size, the next would quadruple it.
                if name.eq_ignore_ascii_case("chaos-setup.exe") {
                    continue;
                }
                println!("cargo:rerun-if-changed={}", p.display());
                files.push((name.to_string(), p));
            }
        }
    }
    files.sort_by(|a, b| a.0.cmp(&b.0));

    src.push_str("pub const FILES: &[File] = &[\n");
    for (name, path) in &files {
        let _ = writeln!(
            src,
            "    File {{ name: {name:?}, bytes: include_bytes!({:?}) }},",
            path.to_string_lossy()
        );
    }
    src.push_str("];\n");

    std::fs::write(&out, src).expect("cannot write payload.rs");
    println!("cargo:warning=chaos-setup embeds {} file(s)", files.len());
}
