//! Constrained decoding: a GBNF grammar or JSON schema, compiled to the set of
//! token ids that may legally come next.
//!
//! # What this is for
//!
//! An agent calling a local model wants the answer to *parse*. Sampling freely
//! and hoping is how you get a JSON reply with a trailing comma, and retrying
//! costs a whole generation. Constrained decoding makes the invalid token
//! unreachable instead: before sampling, every token that would break the
//! grammar has its logit set to `-inf`.
//!
//! # The whole engine hook is one function
//!
//! [`Constraint::allowed`] takes the bytes generated so far and returns a
//! [`TokenMask`]. Applying it is one pass over the logits. Nothing in this
//! crate knows what a model, a graph or a sampler is, and nothing in it depends
//! on `ggml` — it is bytes in, bitset out.
//!
//! ```no_run
//! use chaos_grammar::{Constraint, Grammar};
//!
//! let grammar = Grammar::parse(r#"root ::= "yes" | "no""#).unwrap();
//! // Token id -> its bytes, straight from the container's vocabulary.
//! let vocab: Vec<Vec<u8>> = vec![b"y".to_vec(), b"es".to_vec(), b"no".to_vec()];
//! let constraint = Constraint::new(grammar, &vocab);
//!
//! let mask = constraint.allowed(b"y");
//! assert!(mask.is_allowed(1));   // "es" continues "yes"
//! assert!(!mask.is_allowed(2));  // "no" does not
//! ```
//!
//! # Two ways to be wrong that do not look wrong
//!
//! **A grammar that accepts everything also passes a naive test.** `root ::=
//! .*` constrains nothing, and so does a grammar whose rules failed to parse
//! into anything meaningful. Every test here therefore checks a *rejection* as
//! well as an acceptance.
//!
//! **A mask that is empty stops generation with no error.** If no token is
//! legal the sampler has nothing to pick and the loop ends looking like a
//! well-behaved stop. [`TokenMask::is_empty`] exists so a caller can tell those
//! apart, and [`Constraint::allowed`] documents when it happens.

mod gbnf;
mod matcher;
mod schema;

pub use gbnf::{Element, ElementType};
pub use matcher::Matcher;

use std::fmt;

/// A parsed grammar, ready to constrain a vocabulary.
#[derive(Clone, Debug)]
pub struct Grammar {
    parsed: gbnf::Parsed,
}

impl Grammar {
    /// Parse GBNF text — the format `llama.cpp --grammar` and `--grammar-file`
    /// take.
    pub fn parse(src: &str) -> Result<Self, GrammarError> {
        Ok(Grammar {
            parsed: gbnf::parse(src)?,
        })
    }

    /// Convert a JSON Schema to a grammar, for `--json-schema` and
    /// `--json-schema-file`.
    pub fn from_json_schema(src: &str) -> Result<Self, GrammarError> {
        Self::parse(&schema::to_gbnf(src)?)
    }

    /// The GBNF a JSON Schema converts to, for inspection and for tests that
    /// compare against llama.cpp's own converter.
    pub fn gbnf_for_json_schema(src: &str) -> Result<String, GrammarError> {
        schema::to_gbnf(src)
    }

    /// A fresh matcher at the start of the grammar.
    pub fn matcher(&self) -> Matcher<'_> {
        Matcher::new(&self.parsed)
    }

    /// How many rules the grammar compiled to, including those generated by
    /// desugaring repetitions and groups.
    pub fn rule_count(&self) -> usize {
        self.parsed.rules.len()
    }
}

/// Which token ids may legally come next.
#[derive(Clone, PartialEq, Eq)]
pub struct TokenMask {
    words: Vec<u64>,
    len: usize,
    allowed: usize,
}

impl TokenMask {
    fn new(len: usize) -> Self {
        TokenMask {
            words: vec![0; len.div_ceil(64)],
            len,
            allowed: 0,
        }
    }

    fn allow(&mut self, id: usize) {
        if id < self.len && !self.is_allowed(id) {
            self.words[id / 64] |= 1u64 << (id % 64);
            self.allowed += 1;
        }
    }

    pub fn is_allowed(&self, id: usize) -> bool {
        id < self.len && self.words[id / 64] & (1u64 << (id % 64)) != 0
    }

    /// The number of tokens the vocabulary was built for.
    pub fn len(&self) -> usize {
        self.len
    }

    /// How many tokens are legal.
    pub fn allowed_count(&self) -> usize {
        self.allowed
    }

    /// **No token is legal.** A caller that samples anyway gets whatever the
    /// unmasked logits said, silently violating the grammar; a caller that
    /// masks and samples gets `-inf` everywhere and stops as though the model
    /// had finished. Neither is right, so this is worth checking.
    pub fn is_empty(&self) -> bool {
        self.allowed == 0
    }

    /// Set every disallowed logit to `-inf`, in place.
    ///
    /// The whole integration: call it between building the logits and
    /// sampling. `logits` must be indexed by token id.
    pub fn apply(&self, logits: &mut [f32]) {
        for (id, logit) in logits.iter_mut().enumerate() {
            if !self.is_allowed(id) {
                *logit = f32::NEG_INFINITY;
            }
        }
    }
}

impl fmt::Debug for TokenMask {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "TokenMask({}/{} allowed)", self.allowed, self.len)
    }
}

/// A grammar bound to a vocabulary.
///
/// # Why the vocabulary is bytes and not a tokenizer
///
/// Token text is all this needs, and taking it as `&[impl AsRef<[u8]>]` keeps
/// the crate free of every other crate in the workspace — including the
/// tokenizer. That is what lets it build in the CI job that proves the
/// ggml-free crates work on a machine with no C toolchain.
///
/// The bytes must be the token's **decoded** text, not its stored spelling: a
/// SentencePiece vocabulary writes a leading space as `▁`, and a grammar
/// expecting `" "` would reject every word.
pub struct Constraint<'v> {
    grammar: Grammar,
    vocab: Vec<&'v [u8]>,
    /// Tokens that decode to nothing, which can never advance a grammar and
    /// would otherwise be allowed by every mask — control tokens, mostly.
    empty: Vec<usize>,
}

impl<'v> Constraint<'v> {
    pub fn new<B: AsRef<[u8]>>(grammar: Grammar, vocab: &'v [B]) -> Self {
        let bytes: Vec<&[u8]> = vocab.iter().map(|b| b.as_ref()).collect();
        let empty = bytes
            .iter()
            .enumerate()
            .filter(|(_, b)| b.is_empty())
            .map(|(i, _)| i)
            .collect();
        Constraint {
            grammar,
            vocab: bytes,
            empty,
        }
    }

    pub fn grammar(&self) -> &Grammar {
        &self.grammar
    }

    /// Which tokens may follow `prefix`.
    ///
    /// `prefix` is the raw bytes generated so far under this grammar — not
    /// including the prompt.
    ///
    /// Returns an **empty mask** when the grammar has been fully satisfied and
    /// admits no continuation, and also when `prefix` already violates it. Both
    /// are states a caller must handle rather than sample through; see
    /// [`TokenMask::is_empty`].
    ///
    /// # Cost
    ///
    /// This replays `prefix` from the start on every call, which is O(prefix) —
    /// fine for a one-off check and wasteful in a generation loop. Use
    /// [`Constraint::allowed_from`] with a matcher you keep across tokens.
    pub fn allowed(&self, prefix: &[u8]) -> TokenMask {
        let mut m = self.grammar.matcher();
        match std::str::from_utf8(prefix) {
            Ok(text) => {
                if !m.accept_str(text) {
                    return TokenMask::new(self.vocab.len());
                }
            }
            // A prefix that is not valid UTF-8 cannot have come from this
            // grammar's terminals, which are code points.
            Err(_) => return TokenMask::new(self.vocab.len()),
        }
        self.allowed_from(&m)
    }

    /// Which tokens may follow the state `matcher` is already in.
    ///
    /// The incremental form: advance one matcher as tokens are accepted instead
    /// of replaying the whole prefix each time.
    pub fn allowed_from(&self, matcher: &Matcher<'_>) -> TokenMask {
        let mut mask = TokenMask::new(self.vocab.len());
        if matcher.is_stuck() {
            return mask;
        }
        for (id, bytes) in self.vocab.iter().enumerate() {
            if bytes.is_empty() {
                // Decodes to nothing, so it cannot advance the grammar. Left
                // out deliberately: allowing it lets the model emit control
                // tokens forever without the grammar ever progressing.
                continue;
            }
            if accepts_token(matcher, bytes) {
                mask.allow(id);
            }
        }
        mask
    }

    /// Token ids that decode to no bytes. A caller wiring in EOS handling needs
    /// these, because they are excluded from every mask.
    pub fn empty_tokens(&self) -> &[usize] {
        &self.empty
    }
}

/// Can the grammar consume all of `bytes`?
///
/// The trailing partial character is the subtle part. A token may end half way
/// through a code point — an emoji is four byte-fallback tokens — so the tail
/// is judged on what it could still *become*, not on what it is.
fn accepts_token(matcher: &Matcher<'_>, bytes: &[u8]) -> bool {
    let (text, tail) = match std::str::from_utf8(bytes) {
        Ok(t) => (t, &[][..]),
        Err(e) => {
            let good = e.valid_up_to();
            // An *invalid* sequence, as opposed to an incomplete one, can never
            // become a character.
            if e.error_len().is_some() {
                return false;
            }
            (
                std::str::from_utf8(&bytes[..good]).expect("checked"),
                &bytes[good..],
            )
        }
    };
    let mut m = matcher.clone();
    if !m.accept_str(text) {
        return false;
    }
    if tail.is_empty() {
        return true;
    }
    m.could_still_match(tail)
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GrammarError {
    /// A syntax error, with where it is and what was expected.
    Syntax { at: String, what: String },
    /// A rule was referenced but never defined. Left alone this becomes an
    /// empty rule that matches nothing, masking every token.
    UndefinedRule(String),
    /// The same rule name was defined twice.
    DuplicateRule(String),
    /// No `root` rule, so there is no starting point.
    NoRootRule,
    /// `{m,n}` whose expansion would generate an unreasonable number of rules.
    RepetitionTooLarge,
    /// `<think>`, `<[1000]>` and their `!` forms match tokenizer tokens rather
    /// than text, so they need the vocabulary at parse time.
    TokenLiteralsUnsupported { at: String },
    /// The JSON schema could not be read.
    Schema(String),
    /// A JSON Schema keyword this converter does not implement. Refused by name
    /// rather than ignored, because ignoring a constraint produces a grammar
    /// that is *looser* than asked for and nothing downstream can tell.
    SchemaUnsupported(String),
}

impl fmt::Display for GrammarError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            GrammarError::Syntax { at, what } => write!(f, "grammar syntax error at {at}: {what}"),
            GrammarError::UndefinedRule(n) => write!(
                f,
                "rule `{n}` is used but never defined; it would match nothing and mask every token"
            ),
            GrammarError::DuplicateRule(n) => write!(f, "rule `{n}` is defined more than once"),
            GrammarError::NoRootRule => {
                f.write_str("the grammar has no `root` rule, so there is no starting point")
            }
            GrammarError::RepetitionTooLarge => f.write_str(
                "a repetition would expand to an unreasonable number of rules; reduce the counts",
            ),
            GrammarError::TokenLiteralsUnsupported { at } => write!(
                f,
                "token literals (`<think>`, `<[1000]>`, `!<...>`) are not supported, at {at}: \
                 they match tokenizer tokens rather than text, which needs the vocabulary at \
                 parse time. Express the same text as a string literal if it is not a control token"
            ),
            GrammarError::Schema(m) => write!(f, "cannot read the JSON schema: {m}"),
            GrammarError::SchemaUnsupported(k) => write!(
                f,
                "JSON Schema keyword `{k}` is not supported; ignoring it would produce a grammar \
                 looser than you asked for, so it is refused instead"
            ),
        }
    }
}

impl std::error::Error for GrammarError {}

#[cfg(test)]
mod tests {
    use super::*;

    fn vocab() -> Vec<Vec<u8>> {
        vec![
            b"y".to_vec(),
            b"es".to_vec(),
            b"no".to_vec(),
            b"maybe".to_vec(),
            Vec::new(),
        ]
    }

    #[test]
    fn the_mask_admits_a_continuation_and_refuses_the_rest() {
        let g = Grammar::parse(r#"root ::= "yes" | "no""#).expect("parses");
        let v = vocab();
        let c = Constraint::new(g, &v);

        let start = c.allowed(b"");
        assert!(start.is_allowed(0), "`y` starts yes");
        assert!(start.is_allowed(2), "`no` is a whole alternative");
        assert!(!start.is_allowed(3), "`maybe` is in neither");

        let after_y = c.allowed(b"y");
        assert!(after_y.is_allowed(1), "`es` completes yes");
        assert!(!after_y.is_allowed(2), "`no` cannot follow `y`");
        assert!(!after_y.is_allowed(0));
    }

    /// A grammar that accepts everything passes any test that only checks
    /// acceptance, so the refusal above is the half that carries the weight.
    /// This pins that the mask is not simply all-ones.
    #[test]
    fn a_constraint_actually_constrains() {
        let g = Grammar::parse(r#"root ::= "yes""#).expect("parses");
        let v = vocab();
        let c = Constraint::new(g, &v);
        let mask = c.allowed(b"");
        assert!(mask.allowed_count() < v.len(), "everything was allowed");
        assert_eq!(mask.allowed_count(), 1);
    }

    #[test]
    fn a_completed_grammar_admits_nothing_and_says_so() {
        let g = Grammar::parse(r#"root ::= "no""#).expect("parses");
        let v = vocab();
        let c = Constraint::new(g, &v);
        let mask = c.allowed(b"no");
        assert!(mask.is_empty(), "nothing may follow a completed grammar");
    }

    #[test]
    fn a_prefix_that_already_violates_the_grammar_gives_an_empty_mask() {
        let g = Grammar::parse(r#"root ::= "yes""#).expect("parses");
        let v = vocab();
        let c = Constraint::new(g, &v);
        assert!(c.allowed(b"zzz").is_empty());
    }

    /// A token that decodes to nothing can never advance the grammar, so
    /// allowing it lets the model emit control tokens forever while the
    /// constraint never progresses.
    #[test]
    fn tokens_that_decode_to_nothing_are_never_allowed() {
        let g = Grammar::parse(r#"root ::= "yes""#).expect("parses");
        let v = vocab();
        let c = Constraint::new(g, &v);
        assert!(!c.allowed(b"").is_allowed(4));
        assert_eq!(c.empty_tokens(), &[4]);
    }

    /// A token may end half way through a character. Rejecting that would mask
    /// every byte-fallback token and make non-ASCII output impossible.
    #[test]
    fn a_token_ending_mid_character_is_allowed_if_it_could_still_match() {
        let g = Grammar::parse("root ::= [\u{4e00}-\u{9fff}]+").expect("parses");
        // The three bytes of U+4E2D, split as two tokens.
        let v: Vec<Vec<u8>> = vec![vec![0xE4], vec![0xB8, 0xAD], b"z".to_vec()];
        let c = Constraint::new(g, &v);
        let start = c.allowed(b"");
        assert!(
            start.is_allowed(0),
            "a lead byte could still become a match"
        );
        assert!(!start.is_allowed(2), "an ASCII letter cannot");
    }

    #[test]
    fn apply_sets_disallowed_logits_to_negative_infinity() {
        let g = Grammar::parse(r#"root ::= "no""#).expect("parses");
        let v = vocab();
        let c = Constraint::new(g, &v);
        let mut logits = vec![1.0f32; v.len()];
        c.allowed(b"").apply(&mut logits);
        assert_eq!(logits[2], 1.0, "`no` stays");
        assert!(logits[3].is_infinite() && logits[3].is_sign_negative());
    }

    #[test]
    fn the_incremental_matcher_agrees_with_replaying_the_prefix() {
        let g = Grammar::parse(r#"root ::= "a" "b" "c""#).expect("parses");
        let v: Vec<Vec<u8>> = vec![b"a".to_vec(), b"b".to_vec(), b"c".to_vec()];
        let c = Constraint::new(g, &v);

        let mut m = c.grammar().matcher();
        assert!(m.accept_str("a"));
        let incremental = c.allowed_from(&m);
        let replayed = c.allowed(b"a");
        assert_eq!(incremental, replayed);
        assert!(incremental.is_allowed(1) && !incremental.is_allowed(0));
    }
}
