//! The icon, and the completion list `--completion-bash` prints.
//!
//! The flag list is generated by reading this crate's own source, which is
//! why the generator moved out of `core/arch` with the binary: it named
//! `src/bin/chaos-run.rs`, and that file is `src/main.rs` here.

use std::path::PathBuf;

fn main() {
    chaos_build::embed_icon();
    generate_flag_list();
    println!("cargo:rerun-if-env-changed=GGML_LIB_DIR");
}

/// Extract every `"--flag"` the argument parser matches on, for
/// `--completion-bash`.
///
/// Derived rather than written down, because a hand-kept list is a second
/// enumeration of the flags and it drifts. This file has already shipped a
/// **flag count measured from the help text** that was 25 short of what the
/// parser accepted, for eight commits — and the first hand-written completion
/// list here claimed four flags that do not exist while missing 23 that do.
/// Two of the phantoms (`--keep`, `--tfs`) would have been suggested by the
/// shell and then rejected by the binary, which is worse than not suggesting
/// them at all.
///
/// A crude scan of string literals is the right tool: the parser is one
/// `match` on `&str`, so every arm *is* a literal, and anything clever would
/// be a second thing to keep correct.
fn generate_flag_list() {
    const SRC: &str = "src/main.rs";
    println!("cargo:rerun-if-changed={SRC}");
    let source = std::fs::read_to_string(SRC).unwrap_or_default();

    let mut flags: Vec<String> = Vec::new();
    for part in source.split('"').skip(1).step_by(2) {
        // Long flags only. Short ones are ambiguous to complete and the shell
        // offers little for them anyway.
        if part.starts_with("--")
            && part.len() > 2
            && part[2..]
                .chars()
                .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
        {
            flags.push(part.to_string());
        }
    }
    flags.sort();
    flags.dedup();

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("flags.rs");
    let list = flags.join(" ");
    std::fs::write(
        &out,
        format!("/// Generated by build.rs from {SRC}. Do not edit.\npub const COMPLETION_FLAGS: &str = {list:?};\npub const COMPLETION_FLAG_COUNT: usize = {};\n", flags.len()),
    )
    .expect("write flags.rs");
}
