//! Fail early, and in one sentence, when `ggml` is missing.
//!
//! `chaos-arch` is the only crate that cannot be built without `ggml`: it is
//! the forward pass, and the forward pass is `ggml` graphs. Every other crate in
//! the workspace builds fine without it, which is deliberate — the container,
//! probe and planning tools are useful on a machine that has never compiled a
//! line of C.
//!
//! Without this file the failure is a wall of `unresolved import
//! chaos_ggml::Context` errors, repeated once per module, which says nothing
//! about the actual problem: an environment variable is not set. That is the
//! first thing a new contributor sees, and "the build exploded" is a worse first
//! impression than "you need one more step, here it is".

use std::path::PathBuf;

const REQUIRED: [&str; 3] = ["ggml-base", "ggml-cpu", "ggml"];

fn main() {
    generate_flag_list();
    println!("cargo:rerun-if-env-changed=GGML_LIB_DIR");

    let Some(dir) = std::env::var_os("GGML_LIB_DIR").map(PathBuf::from) else {
        fail("GGML_LIB_DIR is not set.");
    };

    let missing: Vec<&str> = REQUIRED
        .iter()
        .copied()
        .filter(|name| !dir.join(format!("{name}.a")).exists())
        .collect();

    if !missing.is_empty() {
        fail(&format!(
            "GGML_LIB_DIR is {}, but it does not contain: {}",
            dir.display(),
            missing
                .iter()
                .map(|n| format!("{n}.a"))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }
}

/// Extract every `"--flag"` the argument parser matches on, for
/// `--completion-bash`.
///
/// Derived rather than written down, because a hand-kept list is a second
/// enumeration of the flags and it drifts. This file has already shipped a
/// **flag count measured from the help text** that was 25 short of what the
/// parser accepted, for eight commits — and the first hand-written completion
/// list here claimed four flags that do not exist while missing 23 that do.
/// Two of the phantoms (`--keep`, `--tfs`) would have been suggested by the
/// shell and then rejected by the binary, which is worse than not suggesting
/// them at all.
///
/// A crude scan of string literals is the right tool: the parser is one
/// `match` on `&str`, so every arm *is* a literal, and anything clever would
/// be a second thing to keep correct.
fn generate_flag_list() {
    const SRC: &str = "src/bin/chaos-run.rs";
    println!("cargo:rerun-if-changed={SRC}");
    let source = std::fs::read_to_string(SRC).unwrap_or_default();

    let mut flags: Vec<String> = Vec::new();
    for part in source.split('"').skip(1).step_by(2) {
        // Long flags only. Short ones are ambiguous to complete and the shell
        // offers little for them anyway.
        if part.starts_with("--")
            && part.len() > 2
            && part[2..]
                .chars()
                .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
        {
            flags.push(part.to_string());
        }
    }
    flags.sort();
    flags.dedup();

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("flags.rs");
    let list = flags.join(" ");
    std::fs::write(
        &out,
        format!("/// Generated by build.rs from {SRC}. Do not edit.\npub const COMPLETION_FLAGS: &str = {list:?};\npub const COMPLETION_FLAG_COUNT: usize = {};\n", flags.len()),
    )
    .expect("write flags.rs");
}

fn fail(why: &str) -> ! {
    // `cargo:warning` lines survive into the error output and are not truncated
    // the way a panic message can be, so the instructions arrive intact.
    for line in [
        "".to_string(),
        format!("chaos-arch cannot build: {why}"),
        "".to_string(),
        "  chaos-arch is the inference engine and needs ggml's static libraries.".to_string(),
        "  Every other crate in this workspace builds without them.".to_string(),
        "".to_string(),
        "  1. Build ggml once:".to_string(),
        "       git clone https://github.com/ggml-org/llama.cpp".to_string(),
        "       cmake -S llama.cpp -B llama.cpp/build -DCMAKE_BUILD_TYPE=Release \\".to_string(),
        "         -DBUILD_SHARED_LIBS=OFF   # llama.cpp defaults to shared; we need .a".to_string(),
        "       cmake --build llama.cpp/build --config Release -j".to_string(),
        "".to_string(),
        "  2. Point Chaos at the result (the directory holding ggml-base.a,".to_string(),
        "     ggml-cpu.a and ggml.a -- usually llama.cpp/build/ggml/src):".to_string(),
        "       export GGML_LIB_DIR=/path/to/llama.cpp/build/ggml/src".to_string(),
        "       $env:GGML_LIB_DIR = \"C:/path/to/llama.cpp/build/ggml/src\"   # PowerShell"
            .to_string(),
        "".to_string(),
        "  Full instructions: https://github.com/aturzone/Chaos#building".to_string(),
        "".to_string(),
    ] {
        println!("cargo:warning={line}");
    }
    panic!("ggml not found -- see the instructions above");
}
