//! Parsing GBNF text into the element representation the matcher walks.
//!
//! # Why this mirrors llama.cpp's representation rather than improving on it
//!
//! A grammar is a *compatibility surface*: the point of `--grammar` is that a
//! `.gbnf` file written for llama.cpp works here unchanged. Any place where a
//! nicer internal form would round a corner differently is a place where the
//! same file constrains two engines to two different languages — and the
//! failure is not an error, it is output that satisfies one grammar and not the
//! other.
//!
//! So a rule is a flat sequence of [`Element`]s terminated by `End`, with `Alt`
//! separating alternatives, exactly as `llama_grammar_rule` is. Character
//! ranges use the same trailing-modifier encoding: a `Char` optionally followed
//! by `CharRngUpper` to make it a range, and any number of `CharAlt` to add
//! more of either.

use std::collections::HashMap;

use crate::GrammarError;

/// One element of a rule. `value` is a Unicode code point for the character
/// types and a rule index for [`ElementType::RuleRef`].
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub struct Element {
    pub ty: ElementType,
    pub value: u32,
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ElementType {
    /// End of a rule.
    End,
    /// Separates alternatives within a rule.
    Alt,
    /// `value` is an index into the rule table.
    RuleRef,
    /// A literal code point.
    Char,
    /// Inverse: matches any code point **except** those listed. `[^abc]`.
    CharNot,
    /// Modifies the preceding `Char`/`CharAlt` into an inclusive range.
    CharRngUpper,
    /// Adds another alternative to the preceding character set.
    CharAlt,
    /// `.` — any single code point.
    CharAny,
}

impl Element {
    fn new(ty: ElementType, value: u32) -> Self {
        Element { ty, value }
    }
}

pub type Rule = Vec<Element>;

/// A parsed grammar: a rule table plus the index of `root`.
#[derive(Clone, Debug)]
pub struct Parsed {
    pub rules: Vec<Rule>,
    pub root: usize,
}

/// The upper bound llama.cpp puts on rules generated by one repetition, so a
/// grammar like `a{1000}{1000}` is refused rather than allowed to exhaust
/// memory during parsing.
const MAX_REPETITION_THRESHOLD: u64 = 100_000;

struct Parser<'a> {
    src: &'a str,
    /// Byte offset into `src`.
    at: usize,
    rules: Vec<Rule>,
    /// Name → rule index. Rule indices are allocated on first mention, so a
    /// rule may be referenced before it is defined.
    ids: HashMap<String, usize>,
    /// Names that have actually been defined, to catch a reference to a rule
    /// nobody wrote. An undefined rule is not a parse error in the text — it is
    /// an empty rule that silently matches nothing.
    defined: Vec<bool>,
    /// Counter for the generated names of desugared repetitions and groups.
    generated: usize,
}

pub fn parse(src: &str) -> Result<Parsed, GrammarError> {
    let mut p = Parser {
        src,
        at: 0,
        rules: Vec::new(),
        ids: HashMap::new(),
        defined: Vec::new(),
        generated: 0,
    };
    p.skip_space(true);
    while !p.eof() {
        p.parse_rule()?;
        p.skip_space(true);
    }

    // A reference to a rule nobody defined would otherwise become an empty rule
    // that matches nothing, and a grammar that matches nothing is not an error
    // at any later point -- it just masks every token and generation stops.
    for (name, &id) in &p.ids {
        if !p.defined[id] {
            return Err(GrammarError::UndefinedRule(name.clone()));
        }
    }

    let root = *p.ids.get("root").ok_or(GrammarError::NoRootRule)?;
    Ok(Parsed {
        rules: p.rules,
        root,
    })
}

impl<'a> Parser<'a> {
    fn eof(&self) -> bool {
        self.at >= self.src.len()
    }

    fn peek(&self) -> Option<char> {
        self.src[self.at..].chars().next()
    }

    fn bump(&mut self) -> Option<char> {
        let c = self.peek()?;
        self.at += c.len_utf8();
        Some(c)
    }

    fn eat(&mut self, c: char) -> bool {
        if self.peek() == Some(c) {
            self.at += c.len_utf8();
            true
        } else {
            false
        }
    }

    /// The position in `line:column` form, for an error a human can act on.
    fn where_am_i(&self) -> String {
        let upto = &self.src[..self.at.min(self.src.len())];
        let line = upto.matches('\n').count() + 1;
        let col = upto
            .rsplit('\n')
            .next()
            .map(|l| l.chars().count())
            .unwrap_or(0)
            + 1;
        format!("line {line}, column {col}")
    }

    fn err(&self, what: impl Into<String>) -> GrammarError {
        GrammarError::Syntax {
            at: self.where_am_i(),
            what: what.into(),
        }
    }

    /// Skip whitespace and `#` comments.
    ///
    /// `newlines` is false inside a rule body at top level, where a newline
    /// ends the rule — except after `|`, which continues it, and inside
    /// parentheses, which the caller signals by passing true.
    fn skip_space(&mut self, newlines: bool) {
        loop {
            match self.peek() {
                Some(' ') | Some('\t') => {
                    self.at += 1;
                }
                Some('\r') | Some('\n') if newlines => {
                    self.at += 1;
                }
                Some('#') => {
                    while let Some(c) = self.peek() {
                        if c == '\n' {
                            break;
                        }
                        self.at += c.len_utf8();
                    }
                    if !newlines {
                        // The comment ran to end of line; the newline itself
                        // still terminates the rule.
                        return;
                    }
                }
                _ => return,
            }
        }
    }

    fn rule_id(&mut self, name: &str) -> usize {
        if let Some(&id) = self.ids.get(name) {
            return id;
        }
        let id = self.rules.len();
        self.rules.push(Vec::new());
        self.defined.push(false);
        self.ids.insert(name.to_string(), id);
        id
    }

    /// A fresh rule for a desugared group or repetition.
    ///
    /// Named after the rule it came from so a grammar error mentions something
    /// recognisable, and numbered so two `*`s in one rule do not collide.
    fn generated_rule(&mut self, base: &str) -> usize {
        self.generated += 1;
        let name = format!("{base}_{}", self.generated);
        let id = self.rule_id(&name);
        self.defined[id] = true;
        id
    }

    fn parse_name(&mut self) -> Result<String, GrammarError> {
        let start = self.at;
        while let Some(c) = self.peek() {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' {
                self.at += c.len_utf8();
            } else {
                break;
            }
        }
        if start == self.at {
            return Err(self.err("expected a rule name"));
        }
        Ok(self.src[start..self.at].to_string())
    }

    fn parse_rule(&mut self) -> Result<(), GrammarError> {
        let name = self.parse_name()?;
        self.skip_space(false);
        if !(self.eat(':') && self.eat(':') && self.eat('=')) {
            return Err(self.err(format!("expected `::=` after rule name `{name}`")));
        }
        let id = self.rule_id(&name);
        if self.defined[id] {
            return Err(GrammarError::DuplicateRule(name));
        }
        self.defined[id] = true;
        // A newline may follow `::=` before the body starts — `json.gbnf`,
        // `json_arr.gbnf` and `c.gbnf` are all written that way, and three of
        // the eight grammars llama.cpp ships were refused without this.
        // Inside the body a newline still ends the rule.
        self.skip_space(true);

        let mut rule = self.parse_alternates(&name, false)?;
        rule.push(Element::new(ElementType::End, 0));
        self.rules[id] = rule;

        // A rule body ends at the newline. Anything else left on the line is a
        // typo the author would rather hear about than have silently dropped.
        self.skip_space(false);
        match self.peek() {
            None | Some('\n') | Some('\r') => Ok(()),
            Some(c) => Err(self.err(format!("unexpected `{c}` after the rule body"))),
        }
    }

    /// `seq ("|" seq)*`
    fn parse_alternates(&mut self, base: &str, nested: bool) -> Result<Rule, GrammarError> {
        let mut out = self.parse_sequence(base, nested)?;
        self.skip_space(nested);
        while self.peek() == Some('|') {
            self.at += 1;
            // A newline directly after `|` continues the rule even at top
            // level, which is how multi-line alternations are written.
            self.skip_space(true);
            out.push(Element::new(ElementType::Alt, 0));
            out.extend(self.parse_sequence(base, nested)?);
            self.skip_space(nested);
        }
        Ok(out)
    }

    fn parse_sequence(&mut self, base: &str, nested: bool) -> Result<Rule, GrammarError> {
        let mut rule: Rule = Vec::new();
        loop {
            self.skip_space(nested);
            // Where the item that a postfix `*`/`+`/`?`/`{}` would apply to
            // begins. `usize::MAX` means "nothing yet", which makes a leading
            // `*` an error rather than a panic.
            let last_start = rule.len();
            match self.peek() {
                Some('"') => {
                    self.at += 1;
                    while let Some(c) = self.peek() {
                        if c == '"' {
                            break;
                        }
                        let value = self.parse_char_in_literal()?;
                        rule.push(Element::new(ElementType::Char, value));
                    }
                    if !self.eat('"') {
                        return Err(self.err("unterminated string literal"));
                    }
                }
                Some('[') => {
                    self.at += 1;
                    let negated = self.eat('^');
                    let mut first = true;
                    while let Some(c) = self.peek() {
                        if c == ']' {
                            break;
                        }
                        let lo = self.parse_char_in_literal()?;
                        let ty = if first {
                            if negated {
                                ElementType::CharNot
                            } else {
                                ElementType::Char
                            }
                        } else {
                            ElementType::CharAlt
                        };
                        first = false;
                        rule.push(Element::new(ty, lo));
                        // `a-z`, but a trailing `-` before `]` is a literal.
                        if self.peek() == Some('-')
                            && self.src[self.at + 1..].starts_with(|c| c != ']')
                        {
                            self.at += 1;
                            let hi = self.parse_char_in_literal()?;
                            if hi < lo {
                                return Err(self.err("character range runs backwards"));
                            }
                            rule.push(Element::new(ElementType::CharRngUpper, hi));
                        }
                    }
                    if !self.eat(']') {
                        return Err(self.err("unterminated character class"));
                    }
                    if first {
                        return Err(self.err("empty character class"));
                    }
                }
                Some('.') => {
                    self.at += 1;
                    rule.push(Element::new(ElementType::CharAny, 0));
                }
                Some('(') => {
                    self.at += 1;
                    self.skip_space(true);
                    let inner = self.parse_alternates(base, true)?;
                    self.skip_space(true);
                    if !self.eat(')') {
                        return Err(self.err("expected `)`"));
                    }
                    // A group becomes its own rule, because a postfix operator
                    // has to apply to the whole of it and a rule reference is
                    // the only single element that can stand for a sequence.
                    let id = self.generated_rule(base);
                    let mut body = inner;
                    body.push(Element::new(ElementType::End, 0));
                    self.rules[id] = body;
                    rule.push(Element::new(ElementType::RuleRef, id as u32));
                }
                // Token literals: `<think>`, `<[1000]>`, and their `!` forms.
                //
                // Refused rather than guessed. They match *tokenizer tokens*,
                // not text, so resolving one needs the vocabulary at parse
                // time, and a grammar whose token literals were quietly dropped
                // would constrain the model to a different language than the
                // author wrote -- silently, which is this project's most
                // expensive failure mode.
                Some('<') | Some('!') => {
                    return Err(GrammarError::TokenLiteralsUnsupported {
                        at: self.where_am_i(),
                    });
                }
                Some(c) if c.is_ascii_alphanumeric() || c == '-' || c == '_' => {
                    let name = self.parse_name()?;
                    let id = self.rule_id(&name);
                    rule.push(Element::new(ElementType::RuleRef, id as u32));
                }
                // Anything else ends the sequence: `|`, `)`, a newline at top
                // level, or end of input.
                _ => return Ok(rule),
            }

            // Postfix repetition, which may itself be followed by another.
            loop {
                self.skip_space(nested);
                let (min, max) = match self.peek() {
                    Some('*') => {
                        self.at += 1;
                        (0, None)
                    }
                    Some('+') => {
                        self.at += 1;
                        (1, None)
                    }
                    Some('?') => {
                        self.at += 1;
                        (0, Some(1))
                    }
                    Some('{') => {
                        self.at += 1;
                        self.parse_repetition_bounds()?
                    }
                    _ => break,
                };
                self.apply_repetition(base, &mut rule, last_start, min, max)?;
            }
        }
    }

    /// `{m}`, `{m,}` or `{m,n}`, with the opening brace already consumed.
    fn parse_repetition_bounds(&mut self) -> Result<(u64, Option<u64>), GrammarError> {
        self.skip_space(true);
        let min = self.parse_int()?;
        self.skip_space(true);
        let max = if self.eat(',') {
            self.skip_space(true);
            if self.peek() == Some('}') {
                None
            } else {
                Some(self.parse_int()?)
            }
        } else {
            Some(min)
        };
        self.skip_space(true);
        if !self.eat('}') {
            return Err(self.err("expected `}` closing a repetition count"));
        }
        if let Some(max) = max {
            if max < min {
                return Err(self.err("repetition maximum is below its minimum"));
            }
        }
        Ok((min, max))
    }

    fn parse_int(&mut self) -> Result<u64, GrammarError> {
        let start = self.at;
        while matches!(self.peek(), Some(c) if c.is_ascii_digit()) {
            self.at += 1;
        }
        if start == self.at {
            return Err(self.err("expected a number"));
        }
        self.src[start..self.at]
            .parse()
            .map_err(|_| self.err("repetition count is too large"))
    }

    /// Rewrite `rule[from..]` as a repetition, following llama.cpp exactly:
    ///
    /// ```text
    /// S{m,n} --> S S S (m times) S'(n-m)
    ///            S'(x) ::= S S'(x-1) |
    ///            S'(1) ::= S |
    /// S{m,}  --> S S S (m times) S'
    ///            S'    ::= S S' |
    /// S*     --> S'    ::= S S' |
    /// S+     --> S S' ; S' ::= S S' |
    /// S?     --> S'    ::= S |
    /// ```
    ///
    /// The empty alternative in each generated rule is what makes the
    /// repetition able to stop.
    fn apply_repetition(
        &mut self,
        base: &str,
        rule: &mut Rule,
        from: usize,
        min: u64,
        max: Option<u64>,
    ) -> Result<(), GrammarError> {
        if from == rule.len() {
            return Err(self.err("a repetition needs something in front of it"));
        }
        let item: Rule = rule[from..].to_vec();

        // Guard against a grammar whose expansion is enormous. `a{1000}{1000}`
        // is a few characters to write and a million rules to expand.
        let copies = match max {
            Some(n) if n > 0 => n,
            _ => min.max(1),
        };
        if (item.len() as u64).saturating_mul(copies) >= MAX_REPETITION_THRESHOLD {
            return Err(GrammarError::RepetitionTooLarge);
        }

        if min == 0 {
            rule.truncate(from);
        } else {
            for _ in 1..min {
                rule.extend_from_slice(&item);
            }
        }

        match max {
            // Unbounded: one recursive rule, `S' ::= S S' | `.
            None => {
                let id = self.generated_rule(base);
                let mut body = item.clone();
                body.push(Element::new(ElementType::RuleRef, id as u32));
                body.push(Element::new(ElementType::Alt, 0));
                body.push(Element::new(ElementType::End, 0));
                self.rules[id] = body;
                rule.push(Element::new(ElementType::RuleRef, id as u32));
            }
            Some(max) => {
                // `n - m` nested optional rules, innermost first:
                //   S'(1) ::= S |
                //   S'(x) ::= S S'(x-1) |
                let optional = max.saturating_sub(min);
                if optional == 0 {
                    // Exactly `min` copies, all already appended above.
                    return Ok(());
                }
                let mut inner: Option<usize> = None;
                for _ in 0..optional {
                    let id = self.generated_rule(base);
                    let mut body = item.clone();
                    if let Some(prev) = inner {
                        body.push(Element::new(ElementType::RuleRef, prev as u32));
                    }
                    body.push(Element::new(ElementType::Alt, 0));
                    body.push(Element::new(ElementType::End, 0));
                    self.rules[id] = body;
                    inner = Some(id);
                }
                let outermost = inner.expect("optional > 0");
                rule.push(Element::new(ElementType::RuleRef, outermost as u32));
            }
        }
        Ok(())
    }

    /// One character of a string literal or character class, resolving escapes.
    fn parse_char_in_literal(&mut self) -> Result<u32, GrammarError> {
        let c = self
            .bump()
            .ok_or_else(|| self.err("unexpected end of input"))?;
        if c != '\\' {
            return Ok(c as u32);
        }
        let e = self.bump().ok_or_else(|| self.err("trailing backslash"))?;
        Ok(match e {
            'x' => self.parse_hex(2)?,
            'u' => self.parse_hex(4)?,
            'U' => self.parse_hex(8)?,
            't' => '\t' as u32,
            'r' => '\r' as u32,
            'n' => '\n' as u32,
            '\\' => '\\' as u32,
            '"' => '"' as u32,
            '[' => '[' as u32,
            ']' => ']' as u32,
            other => return Err(self.err(format!("unknown escape `\\{other}`"))),
        })
    }

    fn parse_hex(&mut self, digits: usize) -> Result<u32, GrammarError> {
        let start = self.at;
        for _ in 0..digits {
            match self.peek() {
                Some(c) if c.is_ascii_hexdigit() => self.at += 1,
                _ => return Err(self.err(format!("expected {digits} hex digits"))),
            }
        }
        u32::from_str_radix(&self.src[start..self.at], 16)
            .map_err(|_| self.err("invalid hex escape"))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn rules_of(src: &str) -> Parsed {
        parse(src).expect("parses")
    }

    #[test]
    fn a_literal_becomes_one_char_element_per_code_point() {
        let g = rules_of(r#"root ::= "ab""#);
        assert_eq!(
            g.rules[g.root],
            vec![
                Element::new(ElementType::Char, 'a' as u32),
                Element::new(ElementType::Char, 'b' as u32),
                Element::new(ElementType::End, 0),
            ]
        );
    }

    #[test]
    fn a_range_uses_the_trailing_modifier_encoding() {
        let g = rules_of("root ::= [a-z0-9]");
        assert_eq!(
            g.rules[g.root],
            vec![
                Element::new(ElementType::Char, 'a' as u32),
                Element::new(ElementType::CharRngUpper, 'z' as u32),
                Element::new(ElementType::CharAlt, '0' as u32),
                Element::new(ElementType::CharRngUpper, '9' as u32),
                Element::new(ElementType::End, 0),
            ]
        );
    }

    #[test]
    fn a_negated_class_is_char_not() {
        let g = rules_of(r#"root ::= [^\n]"#);
        assert_eq!(g.rules[g.root][0].ty, ElementType::CharNot);
        assert_eq!(g.rules[g.root][0].value, '\n' as u32);
    }

    #[test]
    fn escapes_resolve() {
        let g = rules_of(r#"root ::= "\n\t\\\"\x41B""#);
        let values: Vec<u32> = g.rules[g.root]
            .iter()
            .filter(|e| e.ty == ElementType::Char)
            .map(|e| e.value)
            .collect();
        assert_eq!(values, vec![10, 9, 92, 34, 0x41, 0x42]);
    }

    #[test]
    fn comments_and_blank_lines_are_ignored() {
        let g = parse("# a comment\n\nroot ::= \"a\" # trailing\n").expect("parses");
        assert_eq!(g.rules[g.root].len(), 2);
    }

    /// A newline after `|` continues the rule even at top level. Without this,
    /// every multi-line alternation in `grammars/` fails to parse.
    #[test]
    fn an_alternation_may_span_lines_after_the_bar() {
        let g = rules_of("root ::= \"a\" |\n  \"b\"\n");
        assert!(g.rules[g.root].iter().any(|e| e.ty == ElementType::Alt));
    }

    #[test]
    fn a_rule_may_be_referenced_before_it_is_defined() {
        let g = rules_of("root ::= item\nitem ::= \"x\"\n");
        let r = g.rules[g.root][0];
        assert_eq!(r.ty, ElementType::RuleRef);
        assert_eq!(g.rules[r.value as usize][0].value, 'x' as u32);
    }

    /// An undefined rule is otherwise an empty rule, which matches nothing and
    /// masks every token -- generation just stops, with no error anywhere.
    #[test]
    fn a_reference_to_a_rule_nobody_defined_is_refused() {
        let e = parse("root ::= missing").expect_err("must refuse");
        assert!(matches!(e, GrammarError::UndefinedRule(ref n) if n == "missing"));
    }

    #[test]
    fn a_grammar_without_a_root_is_refused() {
        assert!(matches!(
            parse("item ::= \"x\""),
            Err(GrammarError::NoRootRule)
        ));
    }

    #[test]
    fn a_rule_defined_twice_is_refused() {
        assert!(matches!(
            parse("root ::= \"a\"\nroot ::= \"b\""),
            Err(GrammarError::DuplicateRule(_))
        ));
    }

    #[test]
    fn a_repetition_with_nothing_in_front_is_refused() {
        assert!(parse("root ::= *").is_err());
    }

    /// Token literals need the vocabulary at parse time. Dropping them quietly
    /// would constrain the model to a different language than the author wrote.
    #[test]
    fn token_literals_are_refused_by_name() {
        for src in [
            "root ::= <think> \"a\"",
            "root ::= <[1000]>",
            "root ::= !<think>",
        ] {
            assert!(
                matches!(
                    parse(src),
                    Err(GrammarError::TokenLiteralsUnsupported { .. })
                ),
                "{src} must be refused"
            );
        }
    }

    #[test]
    fn an_absurd_expansion_is_refused_rather_than_attempted() {
        assert!(matches!(
            parse("root ::= \"ab\"{100000}"),
            Err(GrammarError::RepetitionTooLarge)
        ));
    }
}
