//! The grammars llama.cpp ships, and text llama.cpp actually generated under
//! them.
//!
//! # Why this is the only test that proves anything
//!
//! A grammar engine has a failure mode that every hand-written test passes:
//! **a grammar that accepts everything**. `root ::= .*` constrains nothing, and
//! so does a parser that quietly turned a rule it did not understand into an
//! empty one. Checking that valid text is accepted cannot tell those apart from
//! a correct implementation.
//!
//! Two things fix that, and both are here:
//!
//! 1. **Every case checks a rejection as well as an acceptance.** The rejected
//!    string is a one-character edit of the accepted one, so a grammar that has
//!    collapsed into "anything" fails.
//! 2. **The accepted text is llama.cpp's own output**, produced by its grammar
//!    engine under the same grammar at `--temp 0`. If both engines accept the
//!    same real text and reject the same near-misses, they agree about the
//!    language — which is the actual requirement, since the point of
//!    `--grammar` is that a `.gbnf` written for llama.cpp works here unchanged.
//!
//! The grammars and outputs are embedded rather than read from a checkout, so
//! CI — which has no llama.cpp — runs them too. `grammars_shipped_by_llama_cpp`
//! reads the real directory when it is present, which is what catches drift.

use bigtea_grammar::Grammar;

/// `llama.cpp/grammars/json.gbnf`, verbatim.
const JSON: &str = r#"
root   ::= object
value  ::= object | array | string | number | ("true" | "false" | "null") ws

object ::=
  "{" ws (
            string ":" ws value
    ("," ws string ":" ws value)*
  )? "}" ws

array  ::=
  "[" ws (
            value
    ("," ws value)*
  )? "]" ws

string ::=
  "\"" (
    [^"\\\x7F\x00-\x1F] |
    "\\" (["\\bfnrt] | "u" [0-9a-fA-F]{4}) # escapes
  )* "\"" ws

number ::= ("-"? ([0-9] | [1-9] [0-9]{0,15})) ("." [0-9]+)? ([eE] [-+]? [0-9] [1-9]{0,15})? ws

# Optional space: by convention, applied in this grammar after literal chars when allowed
ws ::= | " " | "\n" [ \t]{0,20}
"#;

/// `llama.cpp/grammars/arithmetic.gbnf`, verbatim.
const ARITHMETIC: &str = r#"
root  ::= (expr "=" ws term "\n")+
expr  ::= term ([-+*/] term)*
term  ::= ident | num | "(" ws expr ")" ws
ident ::= [a-z] [a-z0-9_]* ws
num   ::= [0-9]+ ws
ws    ::= [ \t\n]*
"#;

/// `llama.cpp/grammars/list.gbnf`, verbatim.
const LIST: &str = r#"
root ::= item+

# Excludes various line break characters
item ::= "- " [^\r\n\x0b\x0c\x85\u2028\u2029]+ "\n"
"#;

fn accepts_fully(gbnf: &str, text: &str) -> bool {
    let g = Grammar::parse(gbnf).expect("grammar parses");
    let mut m = g.matcher();
    m.accept_str(text) && m.is_complete()
}

fn accepts_prefix(gbnf: &str, text: &str) -> bool {
    let g = Grammar::parse(gbnf).expect("grammar parses");
    let mut m = g.matcher();
    m.accept_str(text)
}

/// Generated by llama.cpp under `json.gbnf`, and it ran to `[end of text]` —
/// so this is a *complete* sentence of the grammar, not merely a prefix.
///
/// ```text
/// llama-completion -m Llama-3.2-1B-Instruct-Q4_K_M.gguf \
///   --grammar-file grammars/json.gbnf --temp 0 -no-cnv -n 60 -c 512 \
///   --no-warmup -p "JSON object describing a person:"
/// ```
const LLAMACPP_JSON_OUTPUT: &str = r#"{"name":"John","age":30,"city":"New York","country":"USA"," occupation":"Software Engineer","address":{"street":"123 Main St","city":"New York","state":"NY","zip":"10001","country":"USA"}}"#;

#[test]
fn llama_cpp_json_output_is_accepted_and_complete() {
    assert!(
        accepts_fully(JSON, LLAMACPP_JSON_OUTPUT),
        "llama.cpp generated this under json.gbnf and we reject it"
    );
}

/// The half that carries the weight. Each of these is a small edit of the
/// output above, invalid in a way JSON actually cares about — an engine whose
/// grammar had collapsed into "accept anything" takes all of them.
#[test]
fn json_near_misses_are_rejected() {
    for (bad, why) in [
        (r#"{"name":"John",}"#, "trailing comma"),
        (r#"{name:"John"}"#, "unquoted key"),
        (r#"{"name":'John'}"#, "single quotes"),
        (r#"{"age":01}"#, "leading zero"),
        (r#"{"name":"John""#, "unclosed object"),
        (r#"{"name":"Jo\qhn"}"#, "invalid escape"),
        ("{\"name\":\"Jo\nhn\"}", "raw control character in a string"),
        (r#"[1,2]"#, "an array where the root demands an object"),
    ] {
        assert!(
            !accepts_fully(JSON, bad),
            "json.gbnf must reject {bad:?} ({why})"
        );
    }
}

/// Generated by llama.cpp under `arithmetic.gbnf`, same command shape. `-n`
/// stopped it mid-expression, so this is a valid **prefix** rather than a
/// complete sentence — `1 \n * 2 \n * 3 ...` is one long `expr` still waiting
/// for its `=`.
const LLAMACPP_ARITHMETIC_OUTPUT: &str = "1\n*2\n*3\n*4\n*5\n*6\n*7\n*8\n*9\n*10\n*11\n";

#[test]
fn llama_cpp_arithmetic_output_is_accepted_as_a_prefix() {
    assert!(accepts_prefix(ARITHMETIC, LLAMACPP_ARITHMETIC_OUTPUT));
    // And it is genuinely incomplete, which is what `-n` cutting it means.
    assert!(
        !accepts_fully(ARITHMETIC, LLAMACPP_ARITHMETIC_OUTPUT),
        "a truncated expression must not read as a finished one"
    );
    // A complete sentence of the grammar.
    assert!(accepts_fully(ARITHMETIC, "a+2=3\n"));
}

#[test]
fn arithmetic_near_misses_are_rejected() {
    for (bad, why) in [
        ("=3\n", "no left-hand side"),
        ("a+2=3", "no newline"),
        ("a++2=3\n", "two operators"),
        ("A+2=3\n", "identifiers are lowercase"),
        ("(a+2=3\n", "unbalanced parenthesis"),
    ] {
        assert!(
            !accepts_fully(ARITHMETIC, bad),
            "arithmetic.gbnf must reject {bad:?} ({why})"
        );
    }
}

/// Generated by llama.cpp under `list.gbnf`; `-n` stopped it before the
/// newline that ends the item, so again a prefix.
const LLAMACPP_LIST_OUTPUT: &str = "- The given problem is to find the value of x in the equation 2x^2 + 5x + 6 = 0. We can use the quadratic formula to solve for x. The quadratic formula is";

#[test]
fn llama_cpp_list_output_is_accepted_as_a_prefix() {
    assert!(accepts_prefix(LIST, LLAMACPP_LIST_OUTPUT));
    assert!(accepts_fully(LIST, "- one\n- two\n"));
}

#[test]
fn list_near_misses_are_rejected() {
    for (bad, why) in [
        ("one\n", "no bullet"),
        ("-one\n", "no space after the dash"),
        ("- \n", "an empty item"),
        ("- a\r\n", "a carriage return is excluded by the class"),
    ] {
        assert!(
            !accepts_fully(LIST, bad),
            "list.gbnf must reject {bad:?} ({why})"
        );
    }
}

/// `ws ::= | " " | ...` — the leading `|` is an empty first alternative, and
/// json.gbnf depends on it after every literal. A parser that choked on it
/// would make `ws` unsatisfiable and reject all valid JSON, which the tests
/// above would catch; a parser that *dropped* it would make whitespace
/// mandatory, which they would not. So it is pinned directly.
#[test]
fn an_empty_first_alternative_is_optional_not_mandatory() {
    let g = Grammar::parse("root ::= \"a\" ws \"b\"\nws ::= | \" \"\n").expect("parses");
    for text in ["ab", "a b"] {
        let mut m = g.matcher();
        assert!(m.accept_str(text) && m.is_complete(), "{text:?}");
    }
}

/// Every grammar in the llama.cpp checkout must parse, when there is one.
///
/// The embedded copies above are a snapshot; this is what notices if upstream
/// changes one or adds a construct we do not handle.
#[test]
fn grammars_shipped_by_llama_cpp_all_parse() {
    let dir = std::env::var("BIGTEA_GBNF_DIR")
        .unwrap_or_else(|_| "C:/Projects/llamacpp-unsloth/grammars".to_string());
    let Ok(entries) = std::fs::read_dir(&dir) else {
        eprintln!("skipping: no grammar directory at {dir}");
        return;
    };
    let mut checked = 0;
    let mut refused = Vec::new();
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("gbnf") {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(&path) else {
            continue;
        };
        checked += 1;
        if let Err(e) = Grammar::parse(&text) {
            refused.push(format!("  {}: {e}", path.display()));
        }
    }
    assert!(checked > 0, "found no .gbnf files in {dir}");
    assert!(
        refused.is_empty(),
        "{} of {checked} shipped grammars were refused:\n{}",
        refused.len(),
        refused.join("\n")
    );
    eprintln!("  {checked} shipped grammars parsed");
}

/// **The schema path, against llama.cpp's own `--json-schema`.**
///
/// This is the converter's oracle. llama.cpp turns the schema into a grammar
/// with `json_schema_to_grammar`, generates under it, and the result must be
/// accepted by the grammar *this* crate produces from the same schema. Two
/// independent converters agreeing on real generated text is the check that
/// matters; comparing the GBNF texts would fail on cosmetic differences and
/// pass on semantic ones.
///
/// ```text
/// llama-completion -m Llama-3.2-1B-Instruct-Q4_K_M.gguf --temp 0 -no-cnv \
///   -n 60 -c 512 --no-warmup -p "A person as JSON:" \
///   --json-schema '{"type":"object","properties":{"name":{"type":"string"},
///                   "age":{"type":"integer"}},"required":["name","age"]}'
///   -> {"name":"John","age":30}
///
/// ... -p "Output JSON:" --json-schema '{"type":"object","properties":{
///       "city":{"type":"string"},"scores":{"type":"array",
///       "items":{"type":"integer"},"minItems":2}},"required":["city","scores"]}'
///   -> {"city": "New York", "scores": [1, 2, 3, 4, 5] }
/// ```
///
/// The second is the interesting one: llama.cpp put spaces after every `:` and
/// `,` and before the closing `}`. A converter that emitted the separators
/// without optional whitespace around them would reject llama.cpp's own output
/// — valid JSON, refused — and no hand-written test would have used that
/// spacing.
#[test]
fn llama_cpp_json_schema_output_is_accepted_by_our_converter() {
    for (schema, output) in [
        (
            r#"{"type":"object","properties":{"name":{"type":"string"},"age":{"type":"integer"}},"required":["name","age"]}"#,
            r#"{"name":"John","age":30}"#,
        ),
        (
            r#"{"type":"object","properties":{"city":{"type":"string"},"scores":{"type":"array","items":{"type":"integer"},"minItems":2}},"required":["city","scores"]}"#,
            r#"{"city": "New York", "scores": [1, 2, 3, 4, 5] }"#,
        ),
    ] {
        let g = Grammar::from_json_schema(schema).expect("converts");
        let mut m = g.matcher();
        let accepted = m.accept_str(output) && m.is_complete();
        assert!(
            accepted,
            "llama.cpp generated {output} under this schema and we reject it"
        );
    }
}

/// And the same schemas must still *refuse* what they should — otherwise the
/// test above is satisfied by a converter that accepts everything.
#[test]
fn the_schema_converter_still_refuses_what_the_schema_forbids() {
    let schema = r#"{"type":"object","properties":{"city":{"type":"string"},"scores":{"type":"array","items":{"type":"integer"},"minItems":2}},"required":["city","scores"]}"#;
    let g = Grammar::from_json_schema(schema).expect("converts");
    for (bad, why) in [
        (r#"{"city":"NY","scores":[1]}"#, "minItems is 2"),
        (r#"{"city":"NY","scores":[]}"#, "empty array"),
        (r#"{"city":"NY"}"#, "a required property is missing"),
        (
            r#"{"city":"NY","scores":["a","b"]}"#,
            "items must be integers",
        ),
        (r#"{"scores":[1,2],"city":"NY"}"#, "required order is fixed"),
        (r#"{"city":"NY","scores":[1,2],"x":1}"#, "an undeclared key"),
    ] {
        let mut m = g.matcher();
        assert!(
            !(m.accept_str(bad) && m.is_complete()),
            "must reject {bad} ({why})"
        );
    }
}

/// A JSON schema and llama.cpp's json.gbnf should agree about ordinary JSON:
/// anything the schema-generated grammar accepts must also be accepted by the
/// generic JSON grammar. They are two independent paths to the same language,
/// so disagreement means one of them is wrong.
#[test]
fn a_schema_generated_grammar_agrees_with_the_generic_json_grammar() {
    let schema = r#"{"type":"object","properties":{"name":{"type":"string"},"age":{"type":"integer"}},"required":["name","age"]}"#;
    let generated = Grammar::from_json_schema(schema).expect("converts");

    let text = r#"{"name":"John","age":30}"#;
    let mut m = generated.matcher();
    assert!(m.accept_str(text) && m.is_complete(), "schema grammar");
    assert!(accepts_fully(JSON, text), "generic json grammar");

    // And the schema is the stricter of the two, as it must be: json.gbnf takes
    // any object, the schema takes only this shape.
    let other = r#"{"unrelated":true}"#;
    assert!(accepts_fully(JSON, other));
    let mut m = generated.matcher();
    assert!(
        !(m.accept_str(other) && m.is_complete()),
        "the schema grammar must be stricter than generic JSON"
    );
}
