#!/usr/bin/env python3
"""Embed `assets/logo.svg` as geometry, not pixels.

Atur: *"the images must be svg exactly, not images -- svg, keep quality with no
quality losing"*. A raster master is sharp at the sizes it was made for and
resampled at every other; the only way to lose nothing is to keep the outlines
and fill them at whatever size is asked for.

So this writes the logo's **flattened outlines**, normalised into a unit square,
and `art::logo_coverage` fills them in Rust at paint time. The window then draws
the mark from geometry at 32 px, at 68 px, or at whatever a high-DPI screen asks
for, with no intermediate bitmap anywhere.

Curves are flattened here rather than in Rust because the cubic subdivision is
the one part that genuinely belongs to the source art: `rasterise-logo.py`
already does it, and doing it twice in two languages is two things to get wrong.
What ships is the polygon soup, which is exact for a fill.

    python tools/make-logo-vector.py

Writes `crates/chaos-app/src/logo_vector.rs`.
"""

import runpy
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Points closer together than this, in units of the mark's own width, are
# collapsed. At 1/2000 of the width that is a quarter-pixel at 512 px -- far
# below anything the window draws -- and it removes most of the points the
# Bezier flattener emits along nearly-straight runs.
MIN_STEP = 0.0005


def main():
    src = ROOT / "tools" / "rasterise-logo.py"
    mod = runpy.run_path(str(src), run_name="make_logo_vector")

    text = (ROOT / "assets" / "logo.svg").read_text(encoding="utf-8")
    paths = mod["parse_paths"](text)
    bx, by, side = mod["ink_box"](paths)

    out_paths = []
    before = after = 0
    for polys, rgb in paths:
        # The art is black on a white plate. A light fill is *paper*: it paints
        # over earlier ink, which is how the eye and the gaps between the rays
        # are cut out. Painting order therefore matters and is preserved.
        lum = (rgb[0] * 299 + rgb[1] * 587 + rgb[2] * 114) // 1000
        ink = lum < 128
        for poly in polys:
            before += len(poly)
            simple = []
            for x, y in poly:
                nx = (x - bx) / side
                ny = (y - by) / side
                if simple:
                    px, py = simple[-1]
                    if abs(nx - px) < MIN_STEP and abs(ny - py) < MIN_STEP:
                        continue
                simple.append((nx, ny))
            # A polygon needs three distinct points to enclose anything.
            if len(simple) < 3:
                continue
            after += len(simple)
            out_paths.append((simple, ink))

    if not out_paths:
        sys.exit("no polygons survived; the SVG or the ink box is wrong")

    lines = []
    for poly, ink in out_paths:
        pts = ", ".join(f"({x:.5},{y:.5})" for x, y in poly)
        lines.append(f"    Poly {{ ink: {str(ink).lower()}, pts: &[{pts}] }},")
    body = "\n".join(lines)

    out = ROOT / "crates" / "chaos-app" / "src" / "logo_vector.rs"
    out.write_text(
        "// GENERATED by tools/make-logo-vector.py from assets/logo.svg -- do not edit.\n"
        "//\n"
        "// The mark's outlines, flattened and normalised into a unit square, in\n"
        "// painting order. `ink: false` is paper: it paints over earlier fills,\n"
        "// which is how the gaps between the rays are cut out.\n"
        "//\n"
        "// This is the whole logo. Nothing here is a bitmap, so the window fills\n"
        "// it at whatever size it needs and loses nothing at any of them.\n"
        "pub struct Poly {\n"
        "    pub ink: bool,\n"
        "    pub pts: &'static [(f32, f32)],\n"
        "}\n"
        "#[rustfmt::skip]\n"
        # A coordinate that happens to equal 0.30103 is log10(2) to clippy,
        # which suggests using the constant. These are points on a drawing.
        "#[allow(clippy::approx_constant)]\n"
        f"pub static POLYS: &[Poly] = &[\n{body}\n];\n",
        encoding="utf-8",
    )
    print(
        f"wrote {out}: {len(out_paths)} polygons, {after} points "
        f"(from {before}, {100 - after * 100 // max(before, 1)}% removed), "
        f"{out.stat().st_size // 1024} KB",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
