#!/usr/bin/env python3
"""Render `assets/logo.svg` at GUI resolution, keeping its antialiasing.

The terminal banner's bitmap (`tools/rasterise-logo.py`) is 56x56 and the window
was drawing *that*, thresholded to one bit and stretched to 30 pixels. Two
things destroy it: 56 is a master size chosen for half-block cells, and
thresholding throws away exactly the coverage that makes a curve look like a
curve. The result was a blue blob, which is what Atur saw and said so.

This writes a second master at 256x256, **8-bit ink coverage rather than
luminance**, so the window can box-filter it down to whatever size it needs and
alpha-blend the result in the theme's own foreground. One source of truth is
still `assets/logo.svg`; this is a second rendering of it, not a second copy.

    python tools/make-logo-alpha.py

Writes `crates/chaos-app/src/logo_hi.rs`.
"""

import runpy
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# 256 is four times the largest size the window draws the mark at, so the box
# filter always has at least a 4x4 footprint per output pixel -- enough to keep
# the rays smooth at 30px, which a 56px master cannot do.
SIZE = 256
# The scanline filler is nearest-neighbour per subsample, so supersampling is
# the only source of edge quality. 6x6 per output pixel at 256 is 1536x1536.
SS = 6


def main():
    # Reuse the rasteriser rather than reimplementing Bezier flattening and
    # nonzero winding a second time. `make-ico.py` does the same.
    src = ROOT / "tools" / "rasterise-logo.py"
    mod = runpy.run_path(str(src), run_name="rasterise_logo")

    text = (ROOT / "assets" / "logo.svg").read_text(encoding="utf-8")
    paths = mod["parse_paths"](text)
    bx, by, side = mod["ink_box"](paths)

    sw = sh = SIZE * SS
    grid = mod["rasterise"](
        paths, SIZE, SIZE, sw, sh, sw / side, sh / side, ss=SS, origin=(bx, by)
    )

    # Coverage, not luminance: 0 is paper, 255 is full ink. The window blends
    # foreground over background by this value, so it never has to know that the
    # source art happens to be black on white.
    ink = [
        [255 - ((px[0] * 299 + px[1] * 587 + px[2] * 114) // 1000) for px in row]
        for row in grid
    ]

    covered = sum(1 for row in ink for v in row if v > 8)
    if covered == 0:
        sys.exit("the render is empty -- the SVG or the ink box is wrong")

    # A coarse eyeball check on the way past, so a broken render shows up in the
    # terminal that ran this rather than in a shipped binary.
    ramp = " .:-=+*#%@"
    step = SIZE // 48
    for y in range(0, SIZE, step * 2):
        sys.stdout.write(
            "".join(ramp[min(9, ink[y][x] * 10 // 256)] for x in range(0, SIZE, step))
            + "\n"
        )

    body = "\n".join(
        "    " + ", ".join(f"0x{v:02x}" for v in row) + "," for row in ink
    )
    out = ROOT / "crates" / "chaos-app" / "src" / "logo_hi.rs"
    out.write_text(
        "// GENERATED by tools/make-logo-alpha.py from assets/logo.svg -- do not edit.\n"
        "//\n"
        "// Ink coverage, one byte per pixel, row-major: 0 is paper, 255 is full\n"
        "// ink. The window box-filters this to the size it needs and blends the\n"
        "// theme's foreground through it, which is why the mark is sharp at any\n"
        "// size and never carries a colour of its own.\n"
        f"pub const HI_W: usize = {SIZE};\n"
        f"pub const HI_H: usize = {SIZE};\n"
        "#[rustfmt::skip]\n"
        f"pub static HI: [u8; {SIZE * SIZE}] = [\n{body}\n];\n",
        encoding="utf-8",
    )
    print(
        f"\nwrote {out} ({SIZE}x{SIZE}, {covered} inked pixels)",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
